version: '3'

services:
  traefik:
    image: traefik:v2.11
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik.toml:/etc/traefik/traefik.toml
    restart: always
    depends_on:
      - mongo
      - deck
      - repository
      - client

  mongo:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodata:/data/db

  messaging:
    build: ./messaging
    labels:
      - traefik.enable=true
      - traefik.http.routers.messaging.rule=Host(`loqi.jiechen.dev`) && PathPrefix(`/api/messaging`)
      - traefik.http.routers.messaging.entrypoints=web
      - traefik.http.middlewares.messaging-ratelimit.ratelimit.average=100
      - traefik.http.middlewares.private-api-allowlist.ipallowlist.sourcerange=172.18.0.1/16
      - traefik.http.routers.messaging.middlewares=messaging-ratelimit, private-api-allowlist
    restart: always

  repository:
    build:
      context: ./repository
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.repository.rule=Host(`loqi.jiechen.dev`) && PathPrefix(`/api/repository`)
      - traefik.http.routers.repository.entrypoints=web
      - traefik.http.middlewares.private-api-allowlist.ipallowlist.sourcerange=172.18.0.1/16
      - traefik.http.routers.repository.middlewares=private-api-allowlist
    restart: always
    # depends_on:
    #   - mongo

  deck:
    build:
      context: ./deck
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.deck.rule=Host(`loqi.jiechen.dev`) && PathPrefix(`/api/deck`)
      - traefik.http.routers.deck.entrypoints=web
      - traefik.http.middlewares.private-api-allowlist.ipallowlist.sourcerange=172.18.0.1/16
      - traefik.http.routers.deck.middlewares=private-api-allowlist
    restart: always
    # depends_on:
    #   - mongo

  client:
    build:
      context: ./neo_client
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.client.rule=Host(`loqi.jiechen.dev`)
      - traefik.http.routers.client.entrypoints=web
    restart: always
    # depends_on:
    #   - repository
    #   - deck



volumes:
  mongodata:
