version: '3'

services:
  traefik:
    image: traefik:v2.10
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik.toml:/etc/traefik/traefik.toml
    restart: always
    depends_on:
      - repository

  repository:
    build:
      context: ./repository
      dockerfile: Dockerfile.dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.home.rule=PathPrefix(`/api/repository`)
      - traefik.http.routers.home.entrypoints=web
    restart: always
