version: '3'

services:
  traefik:
    image: traefik:v2.10
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik.toml:/etc/traefik/traefik.toml
    restart: always
    depends_on:
      - mongo
      - deck
      - repository
      - client

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  repository:
    build:
      context: ./repository
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.repository.rule=PathPrefix(`/api/repository`)
      - traefik.http.routers.repository.entrypoints=web
    restart: always
    depends_on:
      - mongo

  deck:
    build:
      context: ./deck
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.deck.rule=PathPrefix(`/api/deck`)
      - traefik.http.routers.deck.entrypoints=web
    restart: always
    depends_on:
      - mongo

  client:
    build:
      context: ./neo_client
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.client.rule=Host(`loqi.jiechen.dev`)
      - traefik.http.routers.client.entrypoints=web
    restart: always
    depends_on:
      - repository
      - deck
