version: '3'

services:
  traefik:
    image: traefik:v2.11
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
    restart: always
    depends_on:
      - client

  mongo:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodata:/data/db

  client:
    build:
      context: ./neo_client
    labels:
      - traefik.enable=true
      - traefik.http.routers.client.rule=Host(`loqi.jiechen.dev`)
      - traefik.http.routers.client.entrypoints=web
    restart: always

  payment:
    build:
      context: ./payment
    labels:
      - traefik.enable=true
      - traefik.http.routers.payment.rule=Host(`loqi.jiechen.dev`) && PathPrefix(`/api/payment`)
      - traefik.http.routers.payment.entrypoints=web
    depends_on:
      - mongo
      
  stripe-cli:
    image: stripe/stripe-cli
    command: listen --forward-to localhost/api/payment/webhook -e invoice.paid,invoice.payment_failed --api-key sk_test_51Og0zkHuYFk3KBjSVTGTFOPtzRZCJf7HwbfBSIfVUGWe3lrV4aSEi22GjIRaYIdzJW4wl7m6wS0nMsZyTOEJtE5000JK57p8yh
    stdin_open: true
    tty: true
    depends_on:
      - payment
    network_mode: "host"
      
volumes:
  mongodata:
