version: '3'

services:
  traefik:
    image: traefik:v2.11
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik.toml:/etc/traefik/traefik.toml
    restart: always
    depends_on:
      - mongo
      - deck
      - repository
      - client

  mongo:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodata:/data/db

  messaging:
    build: ./messaging
    labels:
      - traefik.enable=true
      - traefik.http.routers.messaging.rule=Host(`loqi.jiechen.dev`) && PathPrefix(`/api/messaging`)
      - traefik.http.routers.messaging.entrypoints=web
      - traefik.http.middlewares.messaging-ratelimit.ratelimit.average=100
      - traefik.http.middlewares.messaging-ratelimit.ratelimit.sourcecriterion.ipstrategy.depth=1
      - traefik.http.routers.messaging.middlewares=messaging-ratelimit
    restart: always

  repository:
    build:
      context: ./repository
      dockerfile: Dockerfile
    labels:
      - traefik.enable=true
      - traefik.http.routers.repository.rule=Host(`loqi.jiechen.dev`) && PathPrefix(`/api/repository`)
      - traefik.http.routers.repository.entrypoints=web
    restart: always
    # depends_on:
    #   - mongo

  deck:
    build:
      context: ./deck
    labels:
      - traefik.enable=true
      - traefik.http.routers.deck.rule=Host(`loqi.jiechen.dev`) && PathPrefix(`/api/deck`)
      - traefik.http.routers.deck.entrypoints=web
      - traefik.http.middlewares.deck-ratelimit.ratelimit.average=100
      - traefik.http.middlewares.deck-ratelimit.ratelimit.sourcecriterion.ipstrategy.depth=1
      - traefik.http.routers.deck.middlewares=deck-ratelimit
    restart: always
    # depends_on:
    #   - mongo

  client:
    build:
      context: ./neo_client
    labels:
      - traefik.enable=true
      - traefik.http.routers.client.rule=Host(`loqi.jiechen.dev`)
      - traefik.http.routers.client.entrypoints=web
    restart: always
    # depends_on:
    #   - repository
    #   - deck

  ai:
    build:
      context: ./ai
    labels:
      - traefik.enable=true
      - traefik.http.routers.ai.rule=Host(`loqi.jiechen.dev`) && PathPrefix(`/api/ai`)
      - traefik.http.routers.ai.entrypoints=web
      - traefik.http.middlewares.ai-ratelimit.ratelimit.average=10
      - traefik.http.middlewares.ai-ratelimit.ratelimit.sourcecriterion.ipstrategy.depth=1
      - traefik.http.routers.messaging.middlewares=ai-ratelimit
      - traefik.http.routers.ai.middlewares=ai-ratelimit
    # restart: on-failure
    depends_on:
      - mongo  

  payment:
    build:
      context: ./payment
    labels:
      - traefik.enable=true
      - traefik.http.routers.payment.rule=Host(`loqi.jiechen.dev`) && PathPrefix(`/api/payment`)
      - traefik.http.routers.payment.entrypoints=web
    depends_on:
      - mongo
      
  stripe-cli:
    image: stripe/stripe-cli
    command: listen --forward-to localhost/api/payment/webhook -e invoice.paid,invoice.payment_failed --api-key sk_test_51Og0zkHuYFk3KBjSVTGTFOPtzRZCJf7HwbfBSIfVUGWe3lrV4aSEi22GjIRaYIdzJW4wl7m6wS0nMsZyTOEJtE5000JK57p8yh
    stdin_open: true
    tty: true
    depends_on:
      - payment
    network_mode: "host"
    
  whoami:
    image: traefik/whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`loqi.jiechen.dev`) && PathPrefix(`/whoami`)
volumes:
  mongodata:
