# openapi2-functions.yaml
swagger: "2.0"
info:
  title: test test.apigateway.loqi-loqi.cloud.goog
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json

host: test-1yd6a1oeh1xjb.apigateway.loqi-loqi.cloud.goog
x-google-endpoints:
  - name: test-1yd6a1oeh1xjb.apigateway.loqi-loqi.cloud.goog
    allowCors: True

paths:
  /decks:
    get:
      summary: Get Deck
      operationId: GETDeck
      x-google-backend:
        address: https://us-east1-loqi-loqi.cloudfunctions.net/deck
        disable_auth: true
      responses:
        "200":
          description: A successful response
          schema:
            type: string
