[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[entryPoints]
  [entryPoints.web]
    address = ":80"

[log]
  level = "INFO"
  format = "common"
  #filePath = "/var/log/traefik.log"

#[accessLog]
#  filePath = "/var/log/access.log"
#  format = "json"
#
#  [accessLog.fields]
#    defaultMode = "keep"
#
#    [accessLog.fields.headers]
#      defaultMode = "drop"
#
#      [accessLog.fields.headers.names]
#        "Cf-connecting-ip" = "keep"
  
[api]
  dashboard = true
  insecure = true

[providers.docker]
  exposedByDefault = false

